"""Add host zone id to Order model

Revision ID: 0a889efbe845
Revises: 2b59bac07ae2
Create Date: 2023-11-03 14:10:24.698932

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a889efbe845"
down_revision = "2b59bac07ae2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column("host_zone_id", sa.Integer(), server_default="1", nullable=False),
    )
    op.create_foreign_key(None, "order", "host_zone", ["host_zone_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order", type_="foreignkey")
    op.drop_column("order", "host_zone_id")
    # ### end Alembic commands ###
