"""Init test

Revision ID: 2626c42aaac9
Revises: 1dfbfc3f8d5c
Create Date: 2023-07-15 22:01:04.170434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2626c42aaac9'
down_revision = '1dfbfc3f8d5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
