"""Add IP Limit

Revision ID: 2b59bac07ae2
Revises: b21f5b2d77ec
Create Date: 2023-10-30 23:27:13.196934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b59bac07ae2"
down_revision = "b21f5b2d77ec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("ip_limit", sa.Integer(), nullable=True))
    op.add_column("order", sa.Column("ip_limit", sa.Integer(), nullable=True))
    op.add_column("service", sa.Column("ip_limit", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service", "ip_limit")
    op.drop_column("order", "ip_limit")
    op.drop_column("account", "ip_limit")
    # ### end Alembic commands ###
