"""Add column enable to service model

Revision ID: 33bad9194cea
Revises: 3b5685f8dd99
Create Date: 2023-10-10 23:33:03.378279

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33bad9194cea"
down_revision = "3b5685f8dd99"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service", sa.Column("enable", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service", "enable")
    # ### end Alembic commands ###
