"""Add referral user id columns to user model

Revision ID: 42f7b8e1a7af
Revises: c48ee34607da
Create Date: 2023-10-17 01:52:26.930226

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42f7b8e1a7af"
down_revision = "c48ee34607da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("referral_user_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_user_referral_user_id"), "user", ["referral_user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_referral_user_id"), table_name="user")
    op.drop_column("user", "referral_user_id")
    # ### end Alembic commands ###
