"""Move some settings to DB

Revision ID: 47010335de98
Revises: a00786a4da47
Create Date: 2024-11-30 22:17:52.510679

"""

from datetime import datetime

from alembic import op
import sqlalchemy as sa

from src import config

# revision identifiers, used by Alembic.
revision = "47010335de98"
down_revision = "a00786a4da47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    config_settings_table = sa.table(
        "config_settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("value_type", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        # Add other columns as needed
    )
    op.bulk_insert(
        config_settings_table,
        [
            {
                "key": "TEST_SERVICE_ID",
                "value": config.TEST_SERVICE_ID,
                "value_type": "int",
                "updated_at": datetime.utcnow(),
            },
            {
                "key": "TELEGRAM_CHANNEL",
                "value": config.TELEGRAM_CHANNEL,
                "value_type": "str",
                "updated_at": datetime.utcnow(),
            },
            {
                "key": "BOT_USER_NAME",
                "value": config.BOT_USER_NAME,
                "value_type": "str",
                "updated_at": datetime.utcnow(),
            },
            {
                "key": "UVICORN_HOST",
                "value": config.UVICORN_HOST,
                "value_type": "str",
                "updated_at": datetime.utcnow(),
            },
            {
                "key": "UVICORN_PORT",
                "value": config.UVICORN_PORT,
                "value_type": "int",
                "updated_at": datetime.utcnow(),
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_config_settings_key"), table_name="config_settings")
    op.create_index("ix_config_settings_key", "config_settings", ["key"], unique=False)
    # ### end Alembic commands ###
