"""Add photo_url and keyboard to Notification Model

Revision ID: 5c89d4bccd15
Revises: b70bc92791cd
Create Date: 2024-07-15 15:29:19.340767

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5c89d4bccd15"
down_revision = "b70bc92791cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification",
        sa.Column("keyboard", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "notification", sa.Column("photo_url", sa.String(length=400), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "photo_url")
    op.drop_column("notification", "keyboard")
    # ### end Alembic commands ###
