"""Create a baseline migrations

Revision ID: 704bb66b328f
Revises: 
Create Date: 2023-08-14 13:21:15.265449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704bb66b328f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
