"""Add HostZone model

Revision ID: 76945c05dad7
Revises: 9b69e8d4688e
Create Date: 2023-10-24 19:49:01.998811

"""

import datetime

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "76945c05dad7"
down_revision = "9b69e8d4688e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    host_zone_table = op.create_table(
        "host_zone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=4000), nullable=True),
        sa.Column("max_account", sa.Integer(), nullable=True),
        sa.Column("enable", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_host_zone_description"), "host_zone", ["description"], unique=False
    )
    op.create_index(op.f("ix_host_zone_id"), "host_zone", ["id"], unique=False)
    op.create_index(
        op.f("ix_host_zone_max_account"), "host_zone", ["max_account"], unique=False
    )
    op.create_index(op.f("ix_host_zone_name"), "host_zone", ["name"], unique=False)

    op.bulk_insert(
        host_zone_table,
        [
            {
                "name": "Traffic Limited Zone",
                "description": "Traffic Limited Zone",
                "max_account": 200,
                "enable": True,
                "created_at": datetime.datetime.utcnow(),
                "modified_at": datetime.datetime.utcnow(),
            },
            {
                "name": "Unlimited Zone",
                "description": "Unlimited Zone",
                "max_account": 200,
                "enable": True,
                "created_at": datetime.datetime.utcnow(),
                "modified_at": datetime.datetime.utcnow(),
            },
        ],
    )

    op.add_column(
        "account",
        sa.Column("host_zone_id", sa.Integer(), nullable=False, server_default=str(1)),
    )
    op.create_foreign_key(None, "account", "host_zone", ["host_zone_id"], ["id"])
    op.add_column(
        "host",
        sa.Column("host_zone_id", sa.Integer(), nullable=False, server_default=str(1)),
    )
    op.create_foreign_key(None, "host", "host_zone", ["host_zone_id"], ["id"])
    op.add_column(
        "service",
        sa.Column("host_zone_id", sa.Integer(), nullable=False, server_default=str(1)),
    )
    op.create_foreign_key(None, "service", "host_zone", ["host_zone_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "service", type_="foreignkey")
    op.drop_column("service", "host_zone_id")
    op.drop_constraint(None, "host", type_="foreignkey")
    op.drop_column("host", "host_zone_id")
    op.drop_constraint(None, "account", type_="foreignkey")
    op.drop_column("account", "host_zone_id")
    op.drop_index(op.f("ix_host_zone_name"), table_name="host_zone")
    op.drop_index(op.f("ix_host_zone_max_account"), table_name="host_zone")
    op.drop_index(op.f("ix_host_zone_id"), table_name="host_zone")
    op.drop_index(op.f("ix_host_zone_description"), table_name="host_zone")
    op.drop_table("host_zone")
    # ### end Alembic commands ###
