"""Add force_join_channel to User model

Revision ID: 77c9260b83e6
Revises: 0a889efbe845
Create Date: 2023-12-19 19:48:06.183658

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77c9260b83e6"
down_revision = "0a889efbe845"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "force_join_channel", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "force_join_channel")
    # ### end Alembic commands ###
