"""Add Reality params to InboundConfig

Revision ID: 82515a1003a8
Revises: 6f6fcd3424aa
Create Date: 2023-10-27 18:09:17.450032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "82515a1003a8"
down_revision = "6f6fcd3424aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inbound_config", sa.Column("pbk", sa.String(length=400), nullable=True)
    )
    op.add_column(
        "inbound_config", sa.Column("sid", sa.String(length=400), nullable=True)
    )
    op.add_column(
        "inbound_config", sa.Column("spx", sa.String(length=400), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inbound_config", "spx")
    op.drop_column("inbound_config", "sid")
    op.drop_column("inbound_config", "pbk")
    # ### end Alembic commands ###
