"""Add Currency Model

Revision ID: afa56238b755
Revises: 5c89d4bccd15
Create Date: 2024-07-30 15:09:06.938616

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "afa56238b755"
down_revision = "5c89d4bccd15"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.BigInteger(), nullable=True),
        sa.Column("symbol", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_index(op.f("ix_currency_id"), "currency", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_currency_id"), table_name="currency")
    op.drop_table("currency")
    # ### end Alembic commands ###
