"""Add SUBSCRIPTION_BASE_URL settings to DB

Revision ID: b1bc7aad133f
Revises: 47010335de98
Create Date: 2024-11-30 22:53:24.042474

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa

from src import config

# revision identifiers, used by Alembic.
revision = 'b1bc7aad133f'
down_revision = '47010335de98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    config_settings_table = sa.table(
        "config_settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("value_type", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        # Add other columns as needed
    )
    op.bulk_insert(
        config_settings_table,
        [
            {
                "key": "SUBSCRIPTION_BASE_URL",
                "value": config.SUBSCRIPTION_BASE_URL,
                "value_type": "str",
                "updated_at": datetime.utcnow(),
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_settings_key'), table_name='config_settings')
    op.create_index('ix_config_settings_key', 'config_settings', ['key'], unique=False)
    # ### end Alembic commands ###
