"""Add InboundFlow type

Revision ID: b21f5b2d77ec
Revises: 82515a1003a8
Create Date: 2023-10-29 21:37:37.774855

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b21f5b2d77ec"
down_revision = "82515a1003a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    inboundflow_enum = postgresql.ENUM(
        "xtls_rprx_vision", "xtls_rprx_vision_udp443", name="inboundflow"
    )
    inboundflow_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inbound",
        sa.Column(
            "flow",
            sa.Enum("xtls_rprx_vision", "xtls_rprx_vision_udp443", name="inboundflow"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    inboundflow_enum = postgresql.ENUM(
        "xtls_rprx_vision", "xtls_rprx_vision_udp443", name="inboundflow"
    )
    inboundflow_enum.drop(op.get_bind())

    op.drop_column("inbound", "flow")
    # ### end Alembic commands ###
