"""Add Club Profile Model

Revision ID: b70bc92791cd
Revises: 318548385b4c
Create Date: 2024-06-23 21:33:21.519266

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b70bc92791cd"
down_revision = "318548385b4c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "club_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("total_score", sa.Integer(), nullable=True),
        sa.Column("total_subset", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_club_profile_id"), "club_profile", ["id"], unique=False)
    op.create_index(
        op.f("ix_club_profile_user_id"), "club_profile", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_club_profile_user_id"), table_name="club_profile")
    op.drop_index(op.f("ix_club_profile_id"), table_name="club_profile")
    op.drop_table("club_profile")
    # ### end Alembic commands ###
