"""Add paid_at and verify to Payment model

Revision ID: b790dc7dcfb7
Revises: c48377f00b65
Create Date: 2025-01-03 17:10:20.049472

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b790dc7dcfb7"
down_revision = "c48377f00b65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("verify", sa.Boolean(), nullable=True))
    op.add_column("payment", sa.Column("paid_at", sa.DateTime(), nullable=True))

    # Update existing records with default values
    op.execute("UPDATE payment SET verify = TRUE WHERE verify IS NULL")
    op.execute("UPDATE payment SET paid_at = created_at WHERE paid_at IS NULL")

    # Then alter the columns to be non-nullable
    op.alter_column("payment", "verify", existing_type=sa.Boolean(), nullable=False)
    op.alter_column("payment", "paid_at", existing_type=sa.DateTime(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment", "paid_at")
    op.drop_column("payment", "verify")
    # ### end Alembic commands ###
