"""Add payment_notice to Payment model

Revision ID: b89acf39a86a
Revises: b790dc7dcfb7
Create Date: 2025-01-03 21:38:45.027982

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b89acf39a86a"
down_revision = "b790dc7dcfb7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment_account",
        sa.Column("payment_notice", sa.String(length=300), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_account", "payment_notice")
    # ### end Alembic commands ###
