"""Add date columns to service model

Revision ID: c48ee34607da
Revises: 33bad9194cea
Create Date: 2023-10-11 00:48:38.518899

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c48ee34607da"
down_revision = "33bad9194cea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("service", sa.Column("modified_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service", "modified_at")
    op.drop_column("service", "created_at")
    # ### end Alembic commands ###
