"""add config settings table

Revision ID: c78517599f01
Revises: 5c89d4bccd15
Create Date: 2024-11-22 12:06:27.272108

"""

from datetime import datetime

from alembic import op
import sqlalchemy as sa

from src import config

# revision identifiers, used by Alembic.
revision = "c78517599f01"
down_revision = "5c89d4bccd15"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    config_settings_table = op.create_table(
        "config_settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("value_type", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        op.f("ix_config_settings_key"), "config_settings", ["key"], unique=True
    )
    op.bulk_insert(
        config_settings_table,
        [
            {
                "key": "TELEGRAM_API_TOKEN",
                "value": config.TELEGRAM_API_TOKEN,
                "value_type": "str",
                "updated_at": datetime.utcnow(),
            },
            {
                "key": "TELEGRAM_PAYMENT_API_TOKEN",
                "value": config.TELEGRAM_PAYMENT_API_TOKEN,
                "value_type": "str",
                "updated_at": datetime.utcnow(),
            },
            {
                "key": "TELEGRAM_ADMIN_ID",
                "value": config.TELEGRAM_ADMIN_ID,
                "value_type": "int",
                "updated_at": datetime.utcnow(),
            },
            {
                "key": "TELEGRAM_ADMIN_USER_NAME",
                "value": config.TELEGRAM_ADMIN_USER_NAME,
                "value_type": "str",
                "updated_at": datetime.utcnow(),
            },
            {
                "key": "UVICORN_SSL_CERTFILE",
                "value": config.UVICORN_SSL_CERTFILE,
                "value_type": "str",
                "updated_at": datetime.utcnow(),
            },
            {
                "key": "UVICORN_SSL_KEYFILE",
                "value": config.UVICORN_SSL_KEYFILE,
                "value_type": "str",
                "updated_at": datetime.utcnow(),
            },
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_config_settings_key"), table_name="config_settings")
    op.drop_table("config_settings")
    # ### end Alembic commands ###
