"""Add some fields to Account model

Revision ID: d986a59ac521
Revises: f452162261a7
Create Date: 2024-05-17 14:59:16.375266

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d986a59ac521"
down_revision = "f452162261a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account", sa.Column("service_title", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "account", sa.Column("user_title", sa.String(length=128), nullable=True)
    )
    op.add_column("account", sa.Column("started_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "started_at")
    op.drop_column("account", "user_title")
    op.drop_column("account", "service_title")
    # ### end Alembic commands ###
