"""add download upload field

Revision ID: edec83074e5e
Revises: 2626c42aaac9
Create Date: 2023-07-15 22:03:50.752522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edec83074e5e'
down_revision = '2626c42aaac9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_used_traffic', sa.Column('download', sa.BigInteger(), nullable=True))
    op.add_column('account_used_traffic', sa.Column('upload', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_used_traffic', 'upload')
    op.drop_column('account_used_traffic', 'download')
    # ### end Alembic commands ###
