"""add send_to_admin to Notification model

Revision ID: f452162261a7
Revises: 56e35f688981
Create Date: 2024-05-13 20:29:53.181363

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f452162261a7"
down_revision = "56e35f688981"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification", sa.Column("send_to_admin", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "send_to_admin")
    # ### end Alembic commands ###
